export const THEME_CHANGE = "THEME_CHANGE";
export const APP_LOADING = "APP_LOADING";
export const APP_LOADED = "APP_LOADED";
export const APP_TITLE_CHANGE = "APP_TITLE_CHANGE";
export const APP_ERROR_CREATED = "APP_ERROR_CREATED";
export const APP_ERROR_DISMISSED = "APP_ERROR_DISMISSED";